const defaultProducts = [
  {
    id: 1,
    name: "Men Grey Hoodie",
    type: "Hoodie",
    price: 49.9,
    ecoScore: 4.5,
    footprint: 3.8,
    materialCO2: 2.3,
    shippingCO2: 1.5,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6UwXPnsh0n675cQhcVynTjhLKXWbVY_T_og&s",
  },
  {
    id: 2,
    name: "Women Striped T-Shirt",
    type: "T-Shirt",
    price: 34.9,
    ecoScore: 4.7,
    footprint: 2.5,
    materialCO2: 1.5,
    shippingCO2: 1.0,
    image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSvonK3uihASiHftWCiFxW48qgV6DyCmHeHCPAL0LzTrZSmyvkL0a4c9DZmnEwTN95D9zopDMvK1kArFoiVzSeOuoJ-_SmQ93gdy04u-FG2K0gJVO3hSrqIh7DUcqwcHsCcNqKZfAc&usqp=CAc",
  },
  {
    id: 3,
    name: "Classic Leather Jacket",
    type: "Jacket",
    price: 149.9,
    ecoScore: 3.2,
    footprint: 12.0,
    materialCO2: 9.0,
    shippingCO2: 3.0,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkDQx00KuShDNWjGZH4KrvLaey-a72mz-vKw&s",
  },
  {
    id: 4,
    name: "Denim Blue Jeans",
    type: "Jeans",
    price: 79.9,
    ecoScore: 3.8,
    footprint: 6.5,
    materialCO2: 4.0,
    shippingCO2: 2.5,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6e0GDIiFZyZcVyXDnxRoJ03XgNH1PX0ECnA&s",
    date: new Date().toISOString(),
  },
  {
    id: 5,
    name: "Eco-friendly Sneakers",
    type: "Shoes",
    price: 99.9,
    ecoScore: 4.6,
    footprint: 4.2,
    materialCO2: 3.0,
    shippingCO2: 1.2,
    image: "https://i.imgur.com/T0aWJ3W.png",
    date: new Date().toISOString(),
  },
  {
    id: 6,
    name: "Organic Cotton Dress",
    type: "Dress",
    price: 89.9,
    ecoScore: 4.8,
    footprint: 3.5,
    materialCO2: 2.0,
    shippingCO2: 1.5,
    image: "https://i.imgur.com/1Q9Z1ZL.png",
    date: new Date().toISOString(),
  },
  {
    id: 7,
    name: "Recycled Backpack",
    type: "Bag",
    price: 59.9,
    ecoScore: 4.9,
    footprint: 2.8,
    materialCO2: 1.6,
    shippingCO2: 1.2,
    image: "https://i.imgur.com/qB0pXRY.png",
    date: new Date().toISOString(),
  },
  {
    id: 8,
    name: "Woolen Winter Scarf",
    type: "Accessories",
    price: 39.9,
    ecoScore: 4.2,
    footprint: 2.2,
    materialCO2: 1.2,
    shippingCO2: 1.0,
    image: "https://i.imgur.com/2zi9jzR.png",
    date: new Date().toISOString(),
  },
];


export default defaultProducts;